### ISSUE TITLE
Mac run it with errors?

### ISSUE THREAD

**Issue by MIkeeJY** [SenyxLois/KeyboxCheckerPython#3]
^CTraceback (most recent call last):
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/hackest/Downloads/KeyboxCheckerPython-main/main.py", line 196, in keybox_check_cli
    status_json = await load_from_url()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/Downloads/KeyboxCheckerPython-main/main.py", line 41, in load_from_url
    async with session.get(url, headers=headers, params=params) as response:
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/client.py", line 1418, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/client.py", line 696, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/connector.py", line 1363, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/connector.py", line 1109, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 89, in start_connection
    sock, _, _ = await _staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohappyeyeballs/_staggered.py", line 160, in staggered_race
    done = await _wait_one(
           ^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohappyeyeballs/_staggered.py", line 41, in _wait_one
    return await wait_next
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hackest/Downloads/KeyboxCheckerPython-main/main.py", line 283, in <module>
    asyncio.run(keybox_check_cli(args.keybox_path))
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

**Comment by SenyxLois** [comment]
Did you do CTRL+C?

**Comment by MIkeeJY** [comment]
@SenyxLois Yes,If I don't  do CTRL+C,it is still hanging out~ like this 
<img width="578" alt="image" src="https://github.com/user-attachments/assets/3cc1ba5d-15f0-4b9d-986e-994b6d397c33">
After a long time，it shows 
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/client.py", line 696, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    raise last_exc
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/connector.py", line 1363, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
    async with ceil_timeout(
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hackest/Downloads/KeyboxCheckerPython-main/main.py", line 196, in keybox_check_cli
    status_json = await load_from_url()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/Downloads/KeyboxCheckerPython-main/main.py", line 41, in load_from_url
    async with session.get(url, headers=headers, params=params) as response:
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/client.py", line 1418, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/site-packages/aiohttp/client.py", line 700, in _request
    raise ConnectionTimeoutError(
aiohttp.client_exceptions.ConnectionTimeoutError: Connection timeout to host https://android.googleapis.com/attestation/status

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hackest/Downloads/KeyboxCheckerPython-main/main.py", line 283, in <module>
    asyncio.run(keybox_check_cli(args.keybox_path))
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hackest/.pyenv/versions/3.12.0/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/hackest/Downloads/KeyboxCheckerPython-main/main.py", line 199, in keybox_check_cli
    with open("res/json/status.json", 'r', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'res/json/status.json'

**Comment by SenyxLois** [comment]
Can you access this website?
[Android keybox api](https://android.googleapis.com/attestation/status)

**Comment by MIkeeJY** [comment]
https://android.googleapis.com/attestation/status  
<img width="479" alt="image" src="https://github.com/user-attachments/assets/fe29d48e-6789-4f6f-b9d6-91e2ccfff7ca">
Yes ofcourse

**Comment by SenyxLois** [comment]
It seem like something is blocking python from accessing internet

**Comment by SenyxLois** [comment]
you might wanna check this

https://stackoverflow.com/questions/69733050/mac-can-acceess-internet-but-r-and-python3-cant

**Comment by MIkeeJY** [comment]
@SenyxLois Thanks a lot,I found that it cuz by proxy config~ Use charles must turn on the enhanced mode！
